const data = {
  products: [
    {
      _id: '1',
      name: 'Gaming chair',
      category: 'chairs',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'anything',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'BoAt Headest',
      category: 'headset',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'keyboard',
      category: 'Keyboard',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'asus-monitor',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'asus',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'logitech mouse',
      category: 'mouse',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'logitech',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'mobile holder',
      category: 'holders',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'holder',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
